<a href="https://colab.research.google.com/github/naffaziy24/anlysis-hotel-reservation/blob/main/Modul_2_FIixx_Midterm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import seaborn as sns
from google.colab import files
import numpy as np

In [ ]:
# Mengimpor dataset
df = pd.read_csv('/content/midterm_hotel_data.csv')
df

,Unnamed: 0,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,...,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,name,email,phone-number,credit_card
0,0,Resort Hotel,0,342.0,2015,July,27,1,NaN,0,...,Transient,0.00,0,0.0,Check-Out,2015-07-01,Ernest Barnes,Ernest.Barnes31@outlook.com,669-792-1661,************4322
1,1,Resort Hotel,0,737.0,2015,July,27,1,0.0,0,...,Transient,0.00,0,0.0,Check-Out,2015-07-01,Andrea Baker,Andrea_Baker94@aol.com,858-637-6955,************9157
2,2,Resort Hotel,0,7.0,2015,July,27,1,NaN,1,...,Transient,75.00,0,NaN,Check-Out,2015-07-02,Rebecca Parker,Rebecca_Parker@comcast.net,652-885-2745,************3734
3,3,Resort Hotel,0,13.0,2015,July,27,1,0.0,1,...,Transient,NaN,0,NaN,Check-Out,2015-07-02,Laura Murray,Laura_M@gmail.com,364-656-8427,************5677
4,4,Resort Hotel,0,NaN,2015,July,27,1,0.0,2,...,Transient,98.00,0,NaN,Check-Out,2015-07-03,Linda Hines,LHines@verizon.com,713-226-5883,************5498
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,119385,City Hotel,0,23.0,2017,August,35,30,2.0,5,...,Transient,NaN,0,0.0,Check-Out,2017-09-06,Claudia Johnson,Claudia.J@yahoo.com,403-092-5582,************8647
119386,119386,City Hotel,0,NaN,2017,August,35,31,NaN,5,...,Transient,225.43,0,2.0,Check-Out,2017-09-07,Wesley Aguilar,WAguilar@xfinity.com,238-763-0612,************4333
119387,119387,City Hotel,0,NaN,2017,August,35,31,2.0,5,...,Transient,157.71,0,NaN,Check-Out,2017-09-07,Mary Morales,Mary_Morales@hotmail.com,395-518-4100,************1821
119388,119388,City Hotel,0,109.0,2017,August,35,31,NaN,5,...,Transient,104.40,0,0.0,Check-Out,2017-09-07,Caroline Conley MD,MD_Caroline@comcast.net,531-528-1017,************7860
119389,119389,City Hotel,0,205.0,2017,August,35,29,NaN,7,...,Transient,151.20,0,NaN,Check-Out,2017-09-07,Ariana Michael,Ariana_M@xfinity.com,422-804-6403,************4482

In [ ]:
# Menampilkan informasi awal untuk melihat tipe data
print("\nInformasi Tipe Data Awal:")
print(df.info())

# Mengecek data duplikat
duplicate_count = df.duplicated().sum()
print(f"\nJumlah data duplikat: {duplicate_count}")

# Mengecek data kosong
missing_values = df.isnull().sum()
print("\nJumlah data kosong di setiap kolom:")
print(missing_values)

Informasi Tipe Data Awal:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 37 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   Unnamed: 0                      119390 non-null  int64
 1   hotel                           119390 non-null  object
 2   is_canceled                     119390 non-null  int64
 3   lead_time                       83573 non-null   float64
 4   arrival_date_year               119390 non-null  int64
 5   arrival_date_month              119390 non-null  object
 6   arrival_date_week_number        119390 non-null  int64
 7   arrival_date_day_of_month       119390 non-null  int64
 8   stays_in_weekend_nights         83573 non-null   float64
 9   stays_in_week_nights            119390 non-null  int64
 10  adults                          83573 non-null   float64
 11  children                        119386 non-null  float64
 12  babies                          119390 non-null  int64
 13  meal                            119390 non-null  object
 14  country                         118902 non-null  object
 15  market_segment                  119390 non-null  object
 16  distribution_channel            119390 non-null  object
 17  is_repeated_guest               119390 non-null  int64
 18  previous_cancellations          119390 non-null  int64
 19  previous_bookings_not_canceled  119390 non-null  int64
 20  reserved_room_type              119390 non-null  object
 21  assigned_room_type              119390 non-null  object
 22  booking_changes                 119390 non-null  int64
 23  deposit_type                    119390 non-null  object
 24  agent                           103050 non-null  float64
 25  company                         6797 non-null    float64
 26  days_in_waiting_list            119390 non-null  int64
 27  customer_type                   119390 non-null  object
 28  adr                             83573 non-null   float64
 29  required_car_parking_spaces     119390 non-null  int64
 30  total_of_special_requests       83573 non-null   float64
 31  reservation_status              119390 non-null  object
 32  reservation_status_date         119390 non-null  object
 33  name                            119390 non-null  object
 34  email                           119390 non-null  object
 35  phone-number                    119390 non-null  object
 36  credit_card                     119390 non-null  object
dtypes: float64(8), int64(13), object(16)
memory usage: 33.7+ MB
None

Jumlah data duplikat: 0

Jumlah data kosong di setiap kolom:
Unnamed: 0                             0
hotel                                  0
is_canceled                            0
lead_time                          35817
arrival_date_year                      0
arrival_date_month                     0
arrival_date_week_number               0
arrival_date_day_of_month              0
stays_in_weekend_nights            35817
stays_in_week_nights                   0
adults                             35817
children                               4
babies                                 0
meal                                   0
country                              488
market_segment                         0
distribution_channel                   0
is_repeated_guest                      0
previous_cancellations                 0
previous_bookings_not_canceled         0
reserved_room_type                     0
assigned_room_type                     0
booking_changes                        0
deposit_type                           0
agent                              16340
company                           112593
days_in_waiting_list                   0
customer_type                          0
adr                                35817
required_car_parking_spaces            0
total_of_special_requests          35817
reservation_status                     0
reservation_status_date                0
name                                   0
email                                  0
phone-number                           0
credit_card                            0
dtype: int64

In [ ]:
# Menghitung statistik deskriptif untuk kolom numerik
desc_stats = df.select_dtypes(include=['float64', 'int64']).agg(['mean', 'median', 'std', 'min', 'max', 'count']).T

# Menambahkan mode secara terpisah (karena mode bisa memiliki lebih dari satu nilai)
desc_stats['mode'] = df.select_dtypes(include=['float64', 'int64']).mode().iloc[0]

# Menampilkan hasil
desc_stats

,mean,median,std,min,max,count,mode
Unnamed: 0,59694.500000,59694.5,34465.068657,0.00,119389.0,119390.0,0.0
is_canceled,0.370416,0.0,0.482918,0.00,1.0,119390.0,0.0
lead_time,104.114965,69.0,106.917703,0.00,737.0,83573.0,0.0
arrival_date_year,2016.156554,2016.0,0.707476,2015.00,2017.0,119390.0,2016.0
arrival_date_week_number,27.165173,28.0,13.605138,1.00,53.0,119390.0,33.0
arrival_date_day_of_month,15.798241,16.0,8.780829,1.00,31.0,119390.0,17.0
stays_in_weekend_nights,0.924366,1.0,0.995809,0.00,19.0,83573.0,0.0
stays_in_week_nights,2.500302,2.0,1.908286,0.00,50.0,119390.0,2.0
adults,1.855934,2.0,0.602225,0.00,55.0,83573.0,2.0
children,0.103890,0.0,0.398561,0.00,10.0,119386.0,0.0
babies,0.007949,0.0,0.097436,0.00,10.0,119390.0,0.0
is_repeated_guest,0.031912,0.0,0.175767,0.00,1.0,119390.0,0.0
previous_cancellations,0.087118,0.0,0.844336,0.00,26.0,119390.0,0.0
previous_bookings_not_canceled,0.137097,0.0,1.497437,0.00,72.0,119390.0,0.0
booking_changes,0.221124,0.0,0.652306,0.00,21.0,119390.0,0.0
agent,86.693382,14.0,110.774548,1.00,535.0,103050.0,9.0
company,189.266735,179.0,131.655015,6.00,543.0,6797.0,40.0
days_in_waiting_list,2.321149,0.0,17.594721,0.00,391.0,119390.0,0.0
adr,101.985427,95.0,48.140440,-6.38,510.0,83573.0,62.0
required_car_parking_spaces,0.062518,0.0,0.245291,0.00,8.0,119390.0,0.0
total_of_special_requests,0.572553,0.0,0.792058,0.00,5.0,83573.0,0.0

In [ ]:
# Mengisi missing value pada kolom yang memiliki kosong dengan mean/median
# Kolom lead_time diisi dengan median
df.loc[:, 'lead_time'] = df['lead_time'].fillna(df['lead_time'].median())
# Kolom stays_in_weekend_nights diisi dengan median
df.loc[:, 'stays_in_weekend_nights'] = df['stays_in_weekend_nights'].fillna(df['stays_in_weekend_nights'].median())
# Kolom adults diisi dengan median
df.loc[:, 'adults'] = df['adults'].fillna(df['adults'].median())
# Kolom country diisi dengan modus
df.loc[:, 'country'] = df['country'].fillna(df['country'].mode()[0])
# Kolom children diisi dengan median
df.loc[:, 'children'] = df['children'].fillna(df['children'].median())
# Kolom adr diisi dengan median
df.loc[:, 'adr'] = df['adr'].fillna(df['adr'].median())
# Kolom total_of_special_requests diisi dengan median
df.loc[:, 'total_of_special_requests'] = df['total_of_special_requests'].fillna(df['total_of_special_requests'].median())
# Kolom company diisi dengan median
df.loc[:, 'company'] = df['company'].fillna(df['company'].median())
# Kolom agent diisi dengan 0
df.loc[:, 'agent'] = df['agent'].fillna(0)

# Menampilkan DataFrame yang diperbarui
print("\nDataFrame setelah mengisi nilai kosong pada kolom yang memiliki nilai kosong:")
print(df[['lead_time', 'stays_in_weekend_nights', 'adults', 'country', 'children', 'adr', 'total_of_special_requests', 'company', 'agent']])

# Mengecek kembali jumlah data kosong setelah pengisian
missing_values_after = df.isnull().sum()
print("\nJumlah data kosong di setiap kolom setelah pengisian:")
print(missing_values_after)

DataFrame setelah mengisi nilai kosong pada kolom yang memiliki nilai kosong:
        lead_time  stays_in_weekend_nights  adults country  children     adr  \
0           342.0                      1.0     2.0     PRT       0.0    0.00
1           737.0                      0.0     2.0     PRT       0.0    0.00
2             7.0                      1.0     1.0     GBR       0.0   75.00
3            13.0                      0.0     1.0     GBR       0.0   95.00
4            69.0                      0.0     2.0     GBR       0.0   98.00
...           ...                      ...     ...     ...       ...     ...
119385       23.0                      2.0     2.0     BEL       0.0   95.00
119386       69.0                      1.0     2.0     FRA       0.0  225.43
119387       69.0                      2.0     2.0     DEU       0.0  157.71
119388      109.0                      1.0     2.0     GBR       0.0  104.40
119389      205.0                      1.0     2.0     DEU       0.0  151.20

        total_of_special_requests  company  agent
0                             0.0    179.0    0.0
1                             0.0    179.0    0.0
2                             0.0    179.0    0.0
3                             0.0    179.0  304.0
4                             0.0    179.0  240.0
...                           ...      ...    ...
119385                        0.0    179.0  394.0
119386                        2.0    179.0    9.0
119387                        0.0    179.0    9.0
119388                        0.0    179.0   89.0
119389                        0.0    179.0    9.0

[119390 rows x 9 columns]

Jumlah data kosong di setiap kolom setelah pengisian:
Unnamed: 0                        0
hotel                             0
is_canceled                       0
lead_time                         0
arrival_date_year                 0
arrival_date_month                0
arrival_date_week_number          0
arrival_date_day_of_month         0
stays_in_weekend_nights           0
stays_in_week_nights              0
adults                            0
children                          0
babies                            0
meal                              0
country                           0
market_segment                    0
distribution_channel              0
is_repeated_guest                 0
previous_cancellations            0
previous_bookings_not_canceled    0
reserved_room_type                0
assigned_room_type                0
booking_changes                   0
deposit_type                      0
agent                             0
company                           0
days_in_waiting_list              0
customer_type                     0
adr                               0
required_car_parking_spaces       0
total_of_special_requests         0
reservation_status                0
reservation_status_date           0
name                              0
email                             0
phone-number                      0
credit_card                       0
dtype: int64

In [ ]:
# MENGECEK OUTLIER SETELAH PENGISIAN MISSING VALEUE
def detect_outliers_iqr(data):

  Q1 = data.quantile(0.25)
  Q3 = data.quantile(0.75)
  IQR = Q3 - Q1
  lower_bound = Q1 - 1.5 * IQR
  upper_bound = Q3 + 1.5 * IQR
  outliers = data[(data < lower_bound) | (data > upper_bound)]
  return outliers

for column in df.columns:
  if pd.api.types.is_numeric_dtype(df[column]):
    outliers = detect_outliers_iqr(df[column])
    if not outliers.empty:
      print(f"Outliers found in column '{column}':")
      print(outliers)
    else:
      print(f"No outliers found in column '{column}'")

No outliers found in column 'Unnamed: 0'
No outliers found in column 'is_canceled'
Outliers found in column 'lead_time':
0         342.0
1         737.0
81        368.0
82        364.0
85        324.0
          ...
119293    243.0
119294    243.0
119296    303.0
119334    325.0
119368    261.0
Name: lead_time, Length: 11132, dtype: float64
No outliers found in column 'arrival_date_year'
No outliers found in column 'arrival_date_week_number'
No outliers found in column 'arrival_date_day_of_month'
Outliers found in column 'stays_in_weekend_nights':
30        4.0
31        4.0
51        3.0
82        3.0
83        3.0
         ...
118570    4.0
118673    4.0
118976    3.0
119083    4.0
119365    3.0
Name: stays_in_weekend_nights, Length: 2408, dtype: float64
Outliers found in column 'stays_in_week_nights':
30        10
31        11
32         8
51         8
52        10
          ..
119255     7
119260     8
119292     8
119369     7
119389     7
Name: stays_in_week_nights, Length: 3354, dtype: int64
Outliers found in column 'adults':
2         1.0
3         1.0
20        1.0
30        1.0
34        3.0
         ...
119365    1.0
119370    1.0
119372    1.0
119376    3.0
119382    3.0
Name: adults, Length: 20852, dtype: float64
Outliers found in column 'children':
13        1.0
45        2.0
55        2.0
65        2.0
87        1.0
         ...
119270    1.0
119287    1.0
119293    2.0
119318    1.0
119319    2.0
Name: children, Length: 8590, dtype: float64
Outliers found in column 'babies':
109       1
111       1
165       1
236       1
264       2
         ..
118437    1
118571    1
118794    1
119098    1
119106    1
Name: babies, Length: 917, dtype: int64
Outliers found in column 'is_repeated_guest':
13937     1
14681     1
14777     1
14817     1
14823     1
         ..
117701    1
117841    1
117961    1
118029    1
119070    1
Name: is_repeated_guest, Length: 3810, dtype: int64
Outliers found in column 'previous_cancellations':
13805     1
13811     1
13825     1
13826     1
13827     1
         ..
111356    1
111357    1
111358    1
111359    1
111925    1
Name: previous_cancellations, Length: 6484, dtype: int64
Outliers found in column 'previous_bookings_not_canceled':
13803     1
13804     2
13805     3
13808     1
13811     1
         ..
117424    1
117841    1
118581    1
118651    1
118654    1
Name: previous_bookings_not_canceled, Length: 3620, dtype: int64
Outliers found in column 'booking_changes':
0         3
1         4
13        1
21        1
22        1
         ..
119355    1
119356    3
119359    1
119362    2
119371    1
Name: booking_changes, Length: 18076, dtype: int64
Outliers found in column 'agent':
4383      375.0
4384      375.0
4385      375.0
4386      375.0
4387      375.0
          ...
119138    394.0
119292    394.0
119357    423.0
119384    394.0
119385    394.0
Name: agent, Length: 1254, dtype: float64
Outliers found in column 'company':
18        110.0
218       110.0
219       110.0
220       110.0
295       113.0
          ...
119119    451.0
119122    451.0
119123    451.0
119124     72.0
119248    485.0
Name: company, Length: 6773, dtype: float64
Outliers found in column 'days_in_waiting_list':
2272      50
2486      47
2487      47
2488      47
2490      47
          ..
111978    36
112021     9
112822    98
114733    59
115990    23
Name: days_in_waiting_list, Length: 3698, dtype: int64
Outliers found in column 'adr':
0           0.00
1           0.00
97        196.54
105       163.00
106       172.00
           ...
119354    195.33
119365    266.75
119382    209.00
119386    225.43
119387    157.71
Name: adr, Length: 13393, dtype: float64
Outliers found in column 'required_car_parking_spaces':
25        1
29        1
53        1
54        1
55        1
         ..
119158    1
119198    1
119236    1
119281    1
119329    1
Name: required_car_parking_spaces, Length: 7416, dtype: int64
Outliers found in column 'total_of_special_requests':
12        3.0
200       3.0
228       3.0
230       3.0
271       3.0
         ...
119248    4.0
119280    3.0
119289    3.0
119290    4.0
119334    4.0
Name: total_of_special_requests, Length: 2005, dtype: float64

In [ ]:
# Menghapus kolom yang tidak mempunyai nama kolom
df = df.loc[:, ~df.columns.str.contains('^Unnamed')]
df

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,name,email,phone-number,credit_card
0,Resort Hotel,0,342.0,2015,July,27,1,1.0,0,2.0,...,Transient,0.00,0,0.0,Check-Out,2015-07-01,Ernest Barnes,Ernest.Barnes31@outlook.com,669-792-1661,************4322
1,Resort Hotel,0,737.0,2015,July,27,1,0.0,0,2.0,...,Transient,0.00,0,0.0,Check-Out,2015-07-01,Andrea Baker,Andrea_Baker94@aol.com,858-637-6955,************9157
2,Resort Hotel,0,7.0,2015,July,27,1,1.0,1,1.0,...,Transient,75.00,0,0.0,Check-Out,2015-07-02,Rebecca Parker,Rebecca_Parker@comcast.net,652-885-2745,************3734
3,Resort Hotel,0,13.0,2015,July,27,1,0.0,1,1.0,...,Transient,95.00,0,0.0,Check-Out,2015-07-02,Laura Murray,Laura_M@gmail.com,364-656-8427,************5677
4,Resort Hotel,0,69.0,2015,July,27,1,0.0,2,2.0,...,Transient,98.00,0,0.0,Check-Out,2015-07-03,Linda Hines,LHines@verizon.com,713-226-5883,************5498
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23.0,2017,August,35,30,2.0,5,2.0,...,Transient,95.00,0,0.0,Check-Out,2017-09-06,Claudia Johnson,Claudia.J@yahoo.com,403-092-5582,************8647
119386,City Hotel,0,69.0,2017,August,35,31,1.0,5,2.0,...,Transient,225.43,0,2.0,Check-Out,2017-09-07,Wesley Aguilar,WAguilar@xfinity.com,238-763-0612,************4333
119387,City Hotel,0,69.0,2017,August,35,31,2.0,5,2.0,...,Transient,157.71,0,0.0,Check-Out,2017-09-07,Mary Morales,Mary_Morales@hotmail.com,395-518-4100,************1821
119388,City Hotel,0,109.0,2017,August,35,31,1.0,5,2.0,...,Transient,104.40,0,0.0,Check-Out,2017-09-07,Caroline Conley MD,MD_Caroline@comcast.net,531-528-1017,************7860
119389,City Hotel,0,205.0,2017,August,35,29,1.0,7,2.0,...,Transient,151.20,0,0.0,Check-Out,2017-09-07,Ariana Michael,Ariana_M@xfinity.com,422-804-6403,************4482

In [ ]:
# Menyimpan DataFrame yang sudah diolah ke dalam file CSV
output_file_path = '/content/processed_hotel_data.csv'
df.to_csv(output_file_path, index=False)
# Mengunduh file CSV yang sudah disimpan
files.download(output_file_path)